[package]
name = "awak"
version = "0.1.0"
authors = ["cssivision <cssivision@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
once_cell = "1.4"
num_cpus = "1.13"
concurrent-queue = "1.1.1"
async-task = "3.0.0"
rand = "0.7"
libc = "0.2"
slab = "0.4"
socket2 = "0.3"
