[package]
name = "awak"
version = "0.1.0"
authors = ["cssivision <cssivision@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
crossbeam = "0.7"
waker-fn = "1.0"
once_cell = "1.4"
num_cpus = "1.13"
