[package]
name = "awak"
version = "0.1.0"
authors = ["cssivision <cssivision@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
async-task = "1"
pin-utils = "0.1"
crossbeam = "0.7"
